from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import core
import os
import subprocess
import threading

app = FastAPI(title="Tor VPN Backend Panel")

# CORS setup
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ensure static directory exists
os.makedirs("static", exist_ok=True)
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/", response_class=HTMLResponse)
async def get_index():
    with open("static/index.html", "r", encoding="utf-8") as f:
        return f.read()

@app.get("/api/status")
async def get_status():
    return core.dashboard_state

class StartConfig(BaseModel):
    max_instances: int = 20

@app.post("/api/start")
async def start_network(config: StartConfig = StartConfig()):
    if core.dashboard_state['status'] == 'running':
        return {"status": "error", "message": "Network is already running"}
    
    # Reset instances to empty to clear old dashboard
    core.dashboard_state['instances'] = {}
    core.start_network(config.max_instances)
    return {"status": "success", "message": "Network starting..."}

@app.post("/api/stop")
async def stop_network():
    core.stop_all()
    return {"status": "success", "message": "Network stopped"}

@app.post("/api/generate_xray")
async def generate_xray():
    try:
        if not os.path.exists("port_mapping.json"):
            return {"status": "error", "message": "No active instances found"}
            
        with open("port_mapping.json", "r") as f:
            mapping = json.load(f)
            
        outbounds = []
        routing_rules = []
        
        server_ip = "172.17.0.1" if platform.system() == 'Linux' else "127.0.0.1"
        
        for port, country in mapping.items():
            tag_name = f"Tor_{country.upper()}"
            outbounds.append({
                "tag": tag_name,
                "protocol": "socks",
                "settings": {
                    "servers": [{"address": server_ip, "port": int(port)}]
                }
            })
            routing_rules.append({
                "type": "field",
                "outboundTag": tag_name,
                "domain": [f"geosite:{country.lower()}"]
            })
            
        config = {
            "remarks": "Auto-Generated by Tor Manager for 3x-ui",
            "outbounds": outbounds,
            "routing": {
                "rules": routing_rules
            }
        }
        
        with open("optimized_config.json", "w") as f:
            json.dump(config, f, indent=4)
            
        return {"status": "success", "message": f"Config generated for {len(outbounds)} nodes!"}
    except Exception as e:
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=54321)
