import json
import copy
import os

class PasarGuardIntegrator:
    def __init__(self, config_path="sample_config.json"):
        with open(config_path, 'r', encoding='utf-8') as f:
            self.config = json.load(f)
            
        # Ensure base structure exists
        if "inbounds" not in self.config:
            self.config["inbounds"] = []
        if "outbounds" not in self.config:
            self.config["outbounds"] = []
        if "routing" not in self.config:
            self.config["routing"] = {"rules": []}
        if "rules" not in self.config["routing"]:
            self.config["routing"]["rules"] = []

    def clone_inbound(self, template_tag, new_tag, new_port, new_host):
        template = None
        for inbound in self.config["inbounds"]:
            if inbound.get("tag") == template_tag:
                template = inbound
                break
                
        if not template:
            raise ValueError(f"Template inbound with tag '{template_tag}' not found.")
            
        # Deep copy to avoid mutating the template
        new_inbound = copy.deepcopy(template)
        new_inbound["tag"] = new_tag
        new_inbound["port"] = new_port
        
        # Inject new Host / SNI into streamSettings
        if "streamSettings" in new_inbound:
            stream = new_inbound["streamSettings"]
            
            # Update TLS serverName (SNI)
            if "tlsSettings" in stream and "serverName" in stream["tlsSettings"]:
                stream["tlsSettings"]["serverName"] = new_host
            if "realitySettings" in stream and "serverNames" in stream["realitySettings"]:
                stream["realitySettings"]["serverNames"] = [new_host]
                
            # Update WS Host
            if "wsSettings" in stream and "headers" in stream["wsSettings"]:
                if "Host" in stream["wsSettings"]["headers"]:
                    stream["wsSettings"]["headers"]["Host"] = new_host
                    
            # Update GRPC Host
            if "grpcSettings" in stream and "authority" in stream["grpcSettings"]:
                stream["grpcSettings"]["authority"] = new_host
                
            # Update HTTP headers
            if "tcpSettings" in stream and "header" in stream["tcpSettings"]:
                if stream["tcpSettings"]["header"].get("type") == "http":
                    request = stream["tcpSettings"]["header"].get("request", {})
                    if "headers" in request and "Host" in request["headers"]:
                        request["headers"]["Host"] = [new_host]
                        
        self.config["inbounds"].append(new_inbound)
        return new_inbound

    def add_tor_outbound(self, country, socks_port):
        outbound_tag = f"outbound-tor-{country.lower()}"
        new_outbound = {
            "tag": outbound_tag,
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1",
                        "port": socks_port
                    }
                ]
            }
        }
        self.config["outbounds"].append(new_outbound)
        return outbound_tag

    def apply_routing(self, inbound_tag, outbound_tag):
        # Insert at the beginning to prioritize
        rule = {
            "type": "field",
            "inboundTag": [inbound_tag],
            "outboundTag": outbound_tag
        }
        self.config["routing"]["rules"].insert(0, rule)

    def add_fallback_routing(self, fallback_outbound_tag):
        # Insert at the end as a catch-all
        rule = {
            "type": "field",
            "network": "tcp,udp",
            "outboundTag": fallback_outbound_tag
        }
        self.config["routing"]["rules"].append(rule)

    def save(self, output_path="optimized_config.json"):
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(self.config, f, indent=4)
        print(f"[OK] Configuration saved to {output_path}")

def main():
    print("==========================================================")
    print("   PasarGuard / Xray OS-Agnostic Core Integrator")
    print("==========================================================")
    
    # Check if port_mapping.json exists (generated by tor_manager.py)
    if not os.path.exists("port_mapping.json"):
        print("[!] port_mapping.json not found. Creating mock mapping for demonstration...")
        mock_data = {
            "9050": "US",
            "9051": "DE",
            "9052": "GB"
        }
        with open("port_mapping.json", "w", encoding='utf-8') as f:
            json.dump(mock_data, f, indent=4)
            
    with open("port_mapping.json", "r", encoding='utf-8') as f:
        port_mapping = json.load(f)
        
    try:
        integrator = PasarGuardIntegrator("sample_config.json")
    except FileNotFoundError:
        print("[Error] sample_config.json not found! Please provide a base Xray config.")
        return
    
    # 1. Iterate over Tor instances and create matching Inbounds and Outbounds
    listen_port_base = 20000
    
    for socks_port, country in port_mapping.items():
        inbound_tag = f"inbound-vless-{country.lower()}"
        host_sni = f"{country.lower()}.my-cdn-domain.com"
        
        # Clone inbound
        try:
            integrator.clone_inbound(
                template_tag="inbound-vless-template",
                new_tag=inbound_tag,
                new_port=listen_port_base,
                new_host=host_sni
            )
            print(f"[+] Created Inbound: {inbound_tag:<20} (Port: {listen_port_base}, SNI: {host_sni})")
        except ValueError as e:
            print(f"[!] {e}")
            return
            
        listen_port_base += 1
        
        # Create SOCKS outbound
        outbound_tag = integrator.add_tor_outbound(country, int(socks_port))
        print(f"[+] Created Outbound: {outbound_tag:<19} (SOCKS: 127.0.0.1:{socks_port})")
        
        # Map routing
        integrator.apply_routing(inbound_tag, outbound_tag)
        print(f"[+] Added Routing:    {inbound_tag} -> {outbound_tag}")
        print("-" * 60)
        
    # 2. Add fallback routing (e.g., direct)
    integrator.add_fallback_routing("direct")
    print("[+] Added Fallback Routing -> 'direct'")
    
    # 3. Save
    integrator.save()

if __name__ == "__main__":
    main()
